---
networks:
  default:
    driver: bridge
services:
  mcbuddy-bot:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add: [ "SYS_PTRACE" ]
    container_name: mcbuddy-bot-dev
    cpus: '0.5'
    env_file: .env.dev
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TZ: ${TZ}
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    mem_limit: 256m
    mem_reservation: 128m
    networks: [ default ]
    restart: unless-stopped
    security_opt: [ "seccomp:unconfined" ]

