---
networks:
  default:
    driver: bridge
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcbuddy_bot
    env_file: .env
    networks: [ default ]
    restart: unless-stopped